using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;
using Microsoft.Data.SqlClient;
using DBMigrator.Api.Models;

namespace DBMigrator.Api.Services
{
    public interface IPostgresWriter
    {
        bool TestConnection(string connectionString, out string error);
        Task PrepareTargetSchemaAsync(string connectionString, List<TableMetadata> tables, bool cleanTarget, Action<string, string> logCallback);
        Task MigrateTableDataAsync(string sqlServerConnStr, string postgresConnStr, TableMetadata table, Action<long> progressCallback, Action<string, string> logCallback, CancellationToken cancellationToken);
        Task ApplyPostDataConstraintsAsync(string connectionString, List<TableMetadata> tables, Action<string, string> logCallback);
    }

    public class PostgresWriter : IPostgresWriter
    {
        public bool TestConnection(string connectionString, out string error)
        {
            try
            {
                using var conn = new NpgsqlConnection(connectionString);
                conn.Open();
                error = string.Empty;
                return true;
            }
            catch (Exception ex)
            {
                error = ex.Message;
                return false;
            }
        }

        private string Quote(string name) => $"\"{name}\"";
        private string QuoteTable(string schema, string table) => $"\"{schema}\".\"{table}\"";

        public async Task PrepareTargetSchemaAsync(string connectionString, List<TableMetadata> tables, bool cleanTarget, Action<string, string> logCallback)
        {
            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync();

            // 1. Ensure schemas exist
            var schemas = tables.Select(t => t.SchemaName).Distinct();
            foreach (var schema in schemas)
            {
                logCallback($"Creating schema {schema} if it does not exist...", "INFO");
                using var cmd = new NpgsqlCommand($"CREATE SCHEMA IF NOT EXISTS {Quote(schema)};", conn);
                await cmd.ExecuteNonQueryAsync();
            }

            // 2. Drop existing tables if clean requested
            if (cleanTarget)
            {
                logCallback("Cleaning target database. Dropping tables in CASCADE mode...", "WARN");
                // Drop in reverse order to reduce dependency issues, though CASCADE handles it
                for (int i = tables.Count - 1; i >= 0; i--)
                {
                    var table = tables[i];
                    var dropQuery = $"DROP TABLE IF EXISTS {QuoteTable(table.SchemaName, table.TableName)} CASCADE;";
                    using var cmd = new NpgsqlCommand(dropQuery, conn);
                    await cmd.ExecuteNonQueryAsync();
                }
            }

            // 3. Create tables with columns and primary keys
            foreach (var table in tables)
            {
                logCallback($"Creating table {table.SchemaName}.{table.TableName}...", "INFO");

                var columnDefs = new List<string>();
                var primaryKeyCols = new List<string>();

                foreach (var col in table.Columns)
                {
                    var colDef = $"{Quote(col.Name)} {col.TargetType}";

                    if (col.IsIdentity)
                    {
                        colDef += " GENERATED BY DEFAULT AS IDENTITY";
                    }

                    if (!col.IsNullable)
                    {
                        colDef += " NOT NULL";
                    }

                    columnDefs.Add(colDef);

                    if (col.IsPrimaryKey)
                    {
                        primaryKeyCols.Add(Quote(col.Name));
                    }
                }

                if (primaryKeyCols.Any())
                {
                    var pkConstraintName = $"PK_{table.TableName}";
                    columnDefs.Add($"CONSTRAINT {Quote(pkConstraintName)} PRIMARY KEY ({string.Join(", ", primaryKeyCols)})");
                }

                var createQuery = $@"
                    CREATE TABLE {QuoteTable(table.SchemaName, table.TableName)} (
                        {string.Join(",\n                        ", columnDefs)}
                    );";

                using var cmd = new NpgsqlCommand(createQuery, conn);
                await cmd.ExecuteNonQueryAsync();
            }
        }

        public async Task MigrateTableDataAsync(
            string sqlServerConnStr, 
            string postgresConnStr, 
            TableMetadata table, 
            Action<long> progressCallback, 
            Action<string, string> logCallback,
            CancellationToken cancellationToken)
        {
            // Connect to SQL Server
            using var sqlConn = new SqlConnection(sqlServerConnStr);
            await sqlConn.OpenAsync(cancellationToken);

            // Connect to Postgres
            using var pgConn = new NpgsqlConnection(postgresConnStr);
            await pgConn.OpenAsync(cancellationToken);

            // Get columns names list
            var colNames = table.Columns.Select(c => Quote(c.Name)).ToList();
            var selectCols = string.Join(", ", table.Columns.Select(c => $"[{c.Name}]"));
            var copyQuery = $"COPY {QuoteTable(table.SchemaName, table.TableName)} ({string.Join(", ", colNames)}) FROM STDIN (FORMAT BINARY)";

            // SQL Server reader
            var sqlQuery = $"SELECT {selectCols} FROM [{table.SchemaName}].[{table.TableName}]";
            using var sqlCmd = new SqlCommand(sqlQuery, sqlConn);
            using var reader = await sqlCmd.ExecuteReaderAsync(cancellationToken);

            // Postgres binary writer
            using var writer = await pgConn.BeginBinaryImportAsync(copyQuery, cancellationToken);

            long rowsCopied = 0;
            var lastUpdate = DateTime.UtcNow;

            while (await reader.ReadAsync(cancellationToken))
            {
                cancellationToken.ThrowIfCancellationRequested();

                await writer.StartRowAsync(cancellationToken);

                for (int i = 0; i < table.Columns.Count; i++)
                {
                    var col = table.Columns[i];
                    var val = reader.GetValue(i);

                    if (val == null || val == DBNull.Value)
                    {
                        await writer.WriteNullAsync(cancellationToken);
                    }
                    else
                    {
                        var converted = ConvertValue(val, col.TargetType);
                        await writer.WriteAsync(converted, cancellationToken);
                    }
                }

                rowsCopied++;

                // Throttled progress reporting every 1000 rows or 200ms
                if (rowsCopied % 1000 == 0 || (DateTime.UtcNow - lastUpdate).TotalMilliseconds > 200)
                {
                    progressCallback(rowsCopied);
                    lastUpdate = DateTime.UtcNow;
                }
            }

            // Final progress update
            progressCallback(rowsCopied);

            // Complete the write operation
            await writer.CompleteAsync(cancellationToken);
            logCallback($"Successfully bulk-copied {rowsCopied:N0} rows into {table.SchemaName}.{table.TableName}", "INFO");
        }

        public async Task ApplyPostDataConstraintsAsync(string connectionString, List<TableMetadata> tables, Action<string, string> logCallback)
        {
            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync();

            // 1. Recreate Indexes
            foreach (var table in tables)
            {
                foreach (var index in table.Indexes)
                {
                    logCallback($"Applying Index {index.IndexName} on {table.SchemaName}.{table.TableName}...", "INFO");
                    
                    var colsStr = string.Join(", ", index.Columns.Select(Quote));
                    var uniqueKeyword = index.IsUnique ? "UNIQUE " : "";
                    
                    // Postgres Index Name formatting: make it unique by table schema if name collisions occur, or keep original
                    var postgresIndexName = $"{table.SchemaName}_{index.IndexName}";
                    
                    var indexQuery = $"CREATE {uniqueKeyword}INDEX IF NOT EXISTS {Quote(postgresIndexName)} ON {QuoteTable(table.SchemaName, table.TableName)} ({colsStr});";
                    
                    try
                    {
                        using var cmd = new NpgsqlCommand(indexQuery, conn);
                        await cmd.ExecuteNonQueryAsync();
                    }
                    catch (Exception ex)
                    {
                        logCallback($"Failed to apply index {index.IndexName}: {ex.Message}", "WARN");
                    }
                }
            }

            // 2. Recreate Foreign Keys
            foreach (var table in tables)
            {
                foreach (var fk in table.ForeignKeys)
                {
                    logCallback($"Applying Foreign Key {fk.ConstraintName} on {table.SchemaName}.{table.TableName}...", "INFO");

                    var colsStr = string.Join(", ", fk.Columns.Select(Quote));
                    
                    // Extract schemas and table names correctly
                    var refParts = fk.ReferencedTableName.Split('.');
                    var refSchema = refParts.Length > 1 ? refParts[0] : "dbo";
                    var refTable = refParts.Length > 1 ? refParts[1] : refParts[0];

                    var refColsStr = string.Join(", ", fk.ReferencedColumns.Select(Quote));

                    var fkQuery = $@"
                        ALTER TABLE {QuoteTable(table.SchemaName, table.TableName)}
                        ADD CONSTRAINT {Quote(fk.ConstraintName)}
                        FOREIGN KEY ({colsStr})
                        REFERENCES {QuoteTable(refSchema, refTable)} ({refColsStr})
                        ON DELETE {fk.OnDeleteAction}
                        ON UPDATE {fk.OnUpdateAction};";

                    try
                    {
                        using var cmd = new NpgsqlCommand(fkQuery, conn);
                        await cmd.ExecuteNonQueryAsync();
                    }
                    catch (Exception ex)
                    {
                        logCallback($"Failed to apply foreign key {fk.ConstraintName}: {ex.Message}", "WARN");
                    }
                }
            }

            // 3. Sync Identity Sequences
            foreach (var table in tables)
            {
                foreach (var col in table.Columns)
                {
                    if (col.IsIdentity)
                    {
                        logCallback($"Syncing sequence generator for identity column {table.SchemaName}.{table.TableName}.{col.Name}...", "INFO");

                        try
                        {
                            // Fetch max value + 1
                            var selectMaxQuery = $"SELECT COALESCE(MAX({Quote(col.Name)}), 0) + 1 FROM {QuoteTable(table.SchemaName, table.TableName)};";
                            long nextVal = 1;
                            using (var maxCmd = new NpgsqlCommand(selectMaxQuery, conn))
                            {
                                var result = await maxCmd.ExecuteScalarAsync();
                                if (result != null && result != DBNull.Value)
                                {
                                    nextVal = Convert.ToInt64(result);
                                }
                            }

                            // Sync sequence using RESTART WITH
                            var alterSeqQuery = $"ALTER TABLE {QuoteTable(table.SchemaName, table.TableName)} ALTER COLUMN {Quote(col.Name)} RESTART WITH {nextVal};";
                            using (var alterCmd = new NpgsqlCommand(alterSeqQuery, conn))
                            {
                                await alterCmd.ExecuteNonQueryAsync();
                            }
                        }
                        catch (Exception ex)
                        {
                            logCallback($"Failed to sync sequence for {table.TableName}.{col.Name}: {ex.Message}", "WARN");
                        }
                    }
                }
            }
        }

        private object ConvertValue(object val, string targetType)
        {
            if (val == null || val == DBNull.Value) return DBNull.Value;

            var targetTypeLower = targetType.ToLower();

            if (targetTypeLower.StartsWith("varchar") || targetTypeLower == "text")
            {
                return val.ToString() ?? string.Empty;
            }

            if (targetTypeLower == "integer")
            {
                return Convert.ToInt32(val);
            }
            if (targetTypeLower == "bigint")
            {
                return Convert.ToInt64(val);
            }
            if (targetTypeLower == "smallint")
            {
                return Convert.ToInt16(val);
            }
            if (targetTypeLower == "boolean")
            {
                return Convert.ToBoolean(val);
            }
            if (targetTypeLower == "double precision")
            {
                return Convert.ToDouble(val);
            }
            if (targetTypeLower == "real")
            {
                return Convert.ToSingle(val);
            }
            if (targetTypeLower.StartsWith("numeric"))
            {
                return Convert.ToDecimal(val);
            }
            if (targetTypeLower == "uuid")
            {
                if (val is Guid g) return g;
                if (val is string s && Guid.TryParse(s, out var parsedGuid)) return parsedGuid;
                return val;
            }
            if (targetTypeLower == "timestamp without time zone")
            {
                if (val is DateTime dt)
                {
                    // Postgres timestamp without timezone cannot accept local times (throws validation error)
                    return new DateTime(dt.Ticks, DateTimeKind.Unspecified);
                }
                return val;
            }
            if (targetTypeLower == "timestamp with time zone")
            {
                if (val is DateTime dt)
                {
                    if (dt.Kind == DateTimeKind.Unspecified)
                    {
                        return new DateTimeOffset(dt, TimeSpan.Zero);
                    }
                    return new DateTimeOffset(dt);
                }
                if (val is DateTimeOffset dto)
                {
                    return dto;
                }
                return val;
            }
            if (targetTypeLower == "bytea")
            {
                if (val is byte[] bytes) return bytes;
                return val;
            }

            return val;
        }
    }
}
